spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaojh222/config-server
server:
  port: 8380
  servlet:
    context-path: /configserver